plugins {
    id 'java'
}

group = 'com.jlcc'
version = '0.0.1-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'

    implementation project(':erp-common')
    implementation project(':erp-infrastructure')
    implementation project(':erp-domain')
    implementation project(':erp-application')


}

test {
    useJUnitPlatform()
}